In [1]:
import numpy as np

### scalar

In [11]:
s = 2
s

2

### 4 ways of creating a vector

In [2]:
# 1. python list type
asList = [1,2,3]
asList

[1, 2, 3]

In [3]:
# 2. NumPy 1D array
asArray = np.array([1,2,3])
asArray

array([1, 2, 3])

In [4]:
# 3. NumPy row vector
rowVec = np.array([ [1,2,3] ]) 
rowVec

array([[1, 2, 3]])

In [5]:
# 4. NumPy column vector
colVec = np.array([ [1],[2],[3] ])
colVec

array([[1],
       [2],
       [3]])

In [8]:
# another way to create NumPy column vector
otherColVec = np.array([ [1,2,3] ]).T
otherColVec

array([[1],
       [2],
       [3]])

In [9]:
# another way to create NumPy column vector (using reshape)
anotherColVec = np.array([ [1,2,3] ])
anotherColVec = anotherColVec.reshape(3, 1)
anotherColVec

array([[1],
       [2],
       [3]])

### Data Shape

In [18]:
# checking orientation by examining variables shape
# dimensions are always listed as (rows , columns)
# print(f'scalar: {s.shape}') 
print(f'scalar: {np.shape(s)}') 
print(f'asList: {np.shape(asList)}') 
print(f'asArray: {asArray.shape}') 
print(f'rowVec: {rowVec.shape}') 
print(f'colVec - method 1: {colVec.shape}') 
print(f'colVec - method 2: {otherColVec.shape}') 
print(f'colVec - method 3: {anotherColVec.shape}') 

scalar: ()
asList: (3,)
asArray: (3,)
rowVec: (1, 3)
colVec - method 1: (3, 1)
colVec - method 2: (3, 1)
colVec - method 3: (3, 1)


### Data Type

In [16]:
# checking data types
print(f'scalar: {type(s)}') 
print(f'asList: {type(asList)}') 
print(f'asArray: {type(asArray)}') 
print(f'rowVec: {type(rowVec)}') 
print(f'colVec - method 1: {type(colVec)}') 
print(f'colVec - method 2: {type(otherColVec)}') 
print(f'colVec - method 3: {type(anotherColVec)}') 

scalar: <class 'int'>
asList: <class 'list'>
asArray: <class 'numpy.ndarray'>
rowVec: <class 'numpy.ndarray'>
colVec - method 1: <class 'numpy.ndarray'>
colVec - method 2: <class 'numpy.ndarray'>
colVec - method 3: <class 'numpy.ndarray'>
