In [1]:
import numpy as np

### 4 ways of creating a vector

In [2]:
# 1. python list type
asList = [1,2,3]
asList

[1, 2, 3]

In [3]:
# 2. NumPy 1D array
asArray = np.array([1,2,3])
asArray

array([1, 2, 3])

In [4]:
# 3. NumPy row vector
rowVec = np.array([ [1,2,3] ]) 
rowVec

array([[1, 2, 3]])

In [5]:
# 4. NumPy column vector
colVec = np.array([ [1],[2],[3] ])
colVec

array([[1],
       [2],
       [3]])

In [6]:
# another way to create NumPy column vector
otherColVec = np.array([ [1,2,3] ]).T
otherColVec

array([[1],
       [2],
       [3]])

In [7]:
# checking orientation by examining variables shape
# dimensions are always listed as (rows , columns)
print(f'asList: {np.shape(asList)}') 
print(f'asArray: {asArray.shape}') 
print(f'rowVec: {rowVec.shape}') 
print(f'colVec: {colVec.shape}') 

asList: (3,)
asArray: (3,)
rowVec: (1, 3)
colVec: (3, 1)
